name: eslint
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.18.3'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
