name: eslint
on:
  pull_request:
    branches: [ master ]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.2'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
